---
- name: Remove invalid docker versions
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker 
    - docker-client
    - docker-client-latest 
    - docker-common 
    - docker-latest 
    - docker-latest-logrotate 
    - docker-logrotate 
    - docker-selinux 
    - docker-engine-selinux 
    - docker-engine

- name: Ensure docker dependencies are present
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Install yum repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker.repo
    owner: root
    group: root
    mode: 0644

- name: Install docker
  yum:
    name: docker-ce
    state: present

- name: Ensure the user is in the docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Enable docker service
  service:
    name: docker
    state: started
    enabled: yes